/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecepcaoRouteImport } from './routes/recepcao'
import { Route as IndexRouteImport } from './routes/index'

const RecepcaoRoute = RecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recepcao': typeof RecepcaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recepcao': typeof RecepcaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recepcao': typeof RecepcaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recepcao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recepcao'
  id: '__root__' | '/' | '/recepcao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecepcaoRoute: typeof RecepcaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recepcao': {
      id: '/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof RecepcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecepcaoRoute: RecepcaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
